---
- hosts: [master]
  become: true
  tasks:
    - name: updating repository index
      apt:
        update_cache: yes

    - name: install apache2 server
      apt:
        name: apache2
        state: latest

    - name: start apache2 service
      service:
        name: apache2
        state: started # restarted, ...
        enabled: yes # start this service even when the server get reboted

    - name: copying file to master server
      tags: copy
      copy:
        src: hello.master.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644
